server:  
    port: 443
    ssl:
      key-store: classpath:www.shipeng1998.com.jks
      key-password: 3m0xpc82q7k6
    servlet: 
       session.timeout: 60000
       contextpath: /mybike
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
        accesslog:
            dir: ../log/access/
            enabled: true
            pattern: "%h %l %u %s %b %D %t \"%r\" \"%{i,Referer}\" \"%{i,User-Agent}\""
            prefix: ibike_access
            suffix: .log
            ratate: true
logging:
    level.root: info
    level.org.spingframework: info
    level.com.yc: info
    file: ../log/mybike.log
swagger:
    enabled: false